/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviekiosk;

import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen Moore
 */
public class KioskGui extends javax.swing.JFrame {

    /**
     * Creates new form GuiKiosk
     */
    Kiosk k = new Kiosk();
    ArrayList<Media> mediaCart = new ArrayList<>();
    Account user = new Account();
    public KioskGui() throws IOException {
        k.load();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        rentButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        reserveButton = new javax.swing.JButton();
        purchaseButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        kioskWelcomeLabel = new javax.swing.JLabel();
        invButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        transaction = new javax.swing.JPanel();
        movieLabel = new javax.swing.JLabel();
        movieField = new javax.swing.JTextField();
        addMovie = new javax.swing.JButton();
        cartList = new javax.swing.JScrollPane();
        titlesText = new javax.swing.JTextArea();
        doTransaction = new javax.swing.JButton();
        returnMenu2 = new javax.swing.JButton();
        historyView = new javax.swing.JPanel();
        jScrollHistory = new javax.swing.JScrollPane();
        historyText = new javax.swing.JTextArea();
        returnMenu = new javax.swing.JButton();
        inventory = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        invWelcomeLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        checkStock = new javax.swing.JButton();
        returnMenu1 = new javax.swing.JButton();
        stockField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Kiosk");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel4.setName("Go"); // NOI18N
        jPanel4.setLayout(new java.awt.CardLayout());

        emailField.setName("emailField"); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        emailLabel.setText("Enter Email:");
        emailLabel.setName("emailLabel"); // NOI18N

        loginButton.setText("Go");
        loginButton.setMaximumSize(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addGap(34, 34, 34)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jPanel4.add(login, "card2");

        menu.setName("menu"); // NOI18N

        rentButton.setText("Rent");
        rentButton.setName("Rent"); // NOI18N
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.setName("Return"); // NOI18N
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        reserveButton.setText("Reserve");
        reserveButton.setName("Reserve"); // NOI18N
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        purchaseButton.setText("Purchase");
        purchaseButton.setName("Purchase"); // NOI18N
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });

        orderButton.setText("Order");
        orderButton.setName("Order"); // NOI18N
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        historyButton.setText("View History");
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });

        invButton.setText("Check Inventory");
        invButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Quit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(invButton)
                        .addGap(35, 35, 35)
                        .addComponent(exitButton))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reserveButton)
                            .addComponent(rentButton)
                            .addComponent(returnButton))
                        .addGap(66, 66, 66)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(historyButton)
                            .addComponent(purchaseButton)
                            .addComponent(orderButton)))
                    .addComponent(kioskWelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(kioskWelcomeLabel)
                .addGap(104, 104, 104)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(rentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reserveButton))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(orderButton)
                        .addGap(16, 16, 16)
                        .addComponent(purchaseButton)))
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnButton))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(historyButton)))
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invButton)
                    .addComponent(exitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(menu, "card3");

        movieLabel.setText("Movie Title:");

        addMovie.setText("Add");
        addMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieActionPerformed(evt);
            }
        });

        titlesText.setEditable(false);
        titlesText.setColumns(20);
        titlesText.setRows(5);
        cartList.setViewportView(titlesText);

        doTransaction.setText("Go");
        doTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doTransactionActionPerformed(evt);
            }
        });

        returnMenu2.setText("Return");
        returnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMenu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transactionLayout = new javax.swing.GroupLayout(transaction);
        transaction.setLayout(transactionLayout);
        transactionLayout.setHorizontalGroup(
            transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionLayout.createSequentialGroup()
                .addGroup(transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(movieLabel)
                        .addGap(50, 50, 50)
                        .addComponent(movieField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactionLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(addMovie))
                    .addGroup(transactionLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(doTransaction)
                        .addGap(21, 21, 21)
                        .addComponent(returnMenu2))
                    .addGroup(transactionLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(cartList, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transactionLayout.setVerticalGroup(
            transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieLabel)
                    .addComponent(movieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doTransaction)
                    .addComponent(returnMenu2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.add(transaction, "card6");

        historyView.setName("historyView"); // NOI18N

        jScrollHistory.setInheritsPopupMenu(true);

        historyText.setEditable(false);
        historyText.setColumns(20);
        historyText.setRows(5);
        jScrollHistory.setViewportView(historyText);

        returnMenu.setText("Return");
        returnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout historyViewLayout = new javax.swing.GroupLayout(historyView);
        historyView.setLayout(historyViewLayout);
        historyViewLayout.setHorizontalGroup(
            historyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollHistory)
                .addContainerGap())
            .addGroup(historyViewLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(returnMenu)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        historyViewLayout.setVerticalGroup(
            historyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(returnMenu))
        );

        jPanel4.add(historyView, "card4");

        inventory.setName("inventory"); // NOI18N

        titleLabel.setText("Title:");

        invWelcomeLabel.setText("Check Inventory ");

        checkStock.setText("Check Stock");
        checkStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStockActionPerformed(evt);
            }
        });

        returnMenu1.setText("Return");
        returnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMenu1ActionPerformed(evt);
            }
        });

        stockField.setEditable(false);
        stockField.setText("           ");

        javax.swing.GroupLayout inventoryLayout = new javax.swing.GroupLayout(inventory);
        inventory.setLayout(inventoryLayout);
        inventoryLayout.setHorizontalGroup(
            inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryLayout.createSequentialGroup()
                .addGroup(inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventoryLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inventoryLayout.createSequentialGroup()
                                .addComponent(checkStock)
                                .addGap(18, 18, 18)
                                .addComponent(returnMenu1))
                            .addComponent(invWelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inventoryLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(titleLabel)
                        .addGap(59, 59, 59)
                        .addGroup(inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        inventoryLayout.setVerticalGroup(
            inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invWelcomeLabel)
                .addGap(71, 71, 71)
                .addGroup(inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkStock)
                    .addComponent(returnMenu1))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jPanel4.add(inventory, "card5");

        getContentPane().add(jPanel4, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        user = k.login(emailField.getText());
        if(user.getID()==-1)
        {
            JOptionPane.showMessageDialog(null, "Email Not Found. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
          CardLayout c1;
          c1 = (CardLayout)(jPanel4.getLayout());
          kioskWelcomeLabel.setText(k.welcome(user));
          c1.next(jPanel4);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
       transaction.setName(rentButton.getName());
       CardLayout c3 = (CardLayout)(jPanel4.getLayout());
       c3.next(jPanel4);
    }//GEN-LAST:event_rentButtonActionPerformed

    private void returnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuActionPerformed
        CardLayout c2 = (CardLayout)(jPanel4.getLayout());
        c2.show(jPanel4, "card3");
    }//GEN-LAST:event_returnMenuActionPerformed

    private void addMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieActionPerformed
        Media m = k.getCatalog().find(movieField.getText());
        if(m.getID()==-1)
        {
            JOptionPane.showMessageDialog(null, "Movie not found.", "Error", 
                    JOptionPane.ERROR_MESSAGE);
            movieField.setText("");
        }
        else
        {    
        
            switch(transaction.getName())
            {
                case "Rent":
                    if(m.getInv()<1)
                    {

                        JOptionPane.showMessageDialog(null, m.getTitle() + " is not in stock.", 
                                "Error", JOptionPane.ERROR_MESSAGE);

                    }
                    else
                    {
                        mediaCart.add(m);
                        StringBuilder s = new StringBuilder(titlesText.getText());
                        s.append(m.getTitle() + "\n");
                        titlesText.setText(s.toString());
                    }
                    break;
                case "Reserve":
                    if(m.getInv()>0)
                    {
                        JOptionPane.showMessageDialog(null, m.getTitle() + " is in stock. Feel free to rent the movie!",
                                "Error", JOptionPane.WARNING_MESSAGE);

                    }
                    else
                    {
                        mediaCart.add(m);
                        StringBuilder s = new StringBuilder(titlesText.getText());
                        s.append(m.getTitle() + "\n");
                        titlesText.setText(s.toString());
                    }
                    break;
                default:
                    mediaCart.add(m);
                    StringBuilder s = new StringBuilder(titlesText.getText());
                    s.append(m.getTitle() + "\n");
                    titlesText.setText(s.toString());
                    break;
            }
        }
    }//GEN-LAST:event_addMovieActionPerformed

    private void doTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doTransactionActionPerformed
        switch(transaction.getName())
        {
            case "Rent":
                k.rentMedia(user,mediaCart);
                break;
            case "Return":
                k.returnMedia(user, mediaCart);
                break;
            case "Reserve":
                k.reserveMedia(user, mediaCart);
                break;
            case "Purchase":
                k.purchaseMedia(user, mediaCart);
                break;
            case "Order":
                k.purchaseMedia(user, mediaCart);
                break;
                
        }
        mediaCart.clear();
        titlesText.setText("");
        JOptionPane.showMessageDialog(null, (transaction.getName() + " completed."));
        CardLayout c4 = (CardLayout)(jPanel4.getLayout());
        c4.previous(jPanel4);
    }//GEN-LAST:event_doTransactionActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        transaction.setName(returnButton.getName());
        CardLayout c3 = (CardLayout)(jPanel4.getLayout());
        c3.next(jPanel4);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonActionPerformed
        transaction.setName(reserveButton.getName());
        CardLayout c3 = (CardLayout)(jPanel4.getLayout());
        c3.next(jPanel4);
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        transaction.setName(purchaseButton.getName());
        CardLayout c3 = (CardLayout)(jPanel4.getLayout());
        c3.next(jPanel4);
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        transaction.setName(orderButton.getName());
        CardLayout c3 = (CardLayout)(jPanel4.getLayout());
        c3.next(jPanel4);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
       CardLayout c5 = (CardLayout)(jPanel4.getLayout());
       
       historyText.setText(k.printHistory(user));
       historyText.setCaretPosition(0); 
       
       c5.show(jPanel4, "card4");
    }//GEN-LAST:event_historyButtonActionPerformed

    private void invButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invButtonActionPerformed
       CardLayout c5 = (CardLayout)(jPanel4.getLayout());
       c5.show(jPanel4, "card5");
    }//GEN-LAST:event_invButtonActionPerformed

    private void returnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenu2ActionPerformed
        CardLayout c2 = (CardLayout)(jPanel4.getLayout());
        c2.show(jPanel4, "card3");
        
        mediaCart.clear();
        titlesText.setText("");
    }//GEN-LAST:event_returnMenu2ActionPerformed

    private void returnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenu1ActionPerformed
        CardLayout c2 = (CardLayout)(jPanel4.getLayout());
        c2.show(jPanel4, "card3");
    }//GEN-LAST:event_returnMenu1ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        try {
            k.save();
        } catch (IOException ex) {
            Logger.getLogger(KioskGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void checkStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStockActionPerformed
        Media m = k.getCatalog().find(titleField.getText());
        if(m.getID()==-1)
           {
                JOptionPane.showMessageDialog(null, "Movie not found.", "Error", 
                    JOptionPane.ERROR_MESSAGE);
                movieField.setText("");
        }        
        else                
            stockField.setText(Integer.toString(m.getInv()));
    }//GEN-LAST:event_checkStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KioskGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KioskGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KioskGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KioskGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KioskGui().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(KioskGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMovie;
    private javax.swing.JScrollPane cartList;
    private javax.swing.JButton checkStock;
    private javax.swing.JButton doTransaction;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JTextArea historyText;
    private javax.swing.JPanel historyView;
    private javax.swing.JButton invButton;
    private javax.swing.JLabel invWelcomeLabel;
    private javax.swing.JPanel inventory;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollHistory;
    private javax.swing.JLabel kioskWelcomeLabel;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField movieField;
    private javax.swing.JLabel movieLabel;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JButton rentButton;
    private javax.swing.JButton reserveButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton returnMenu;
    private javax.swing.JButton returnMenu1;
    private javax.swing.JButton returnMenu2;
    private javax.swing.JTextField stockField;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextArea titlesText;
    private javax.swing.JPanel transaction;
    // End of variables declaration//GEN-END:variables
}
